[package]
name = "rustBotProject"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { version = "0.26", features = ["termion"] }
termion = "3.0"
crossterm = "0.27"
noise = "0.7"
rand = "0.8"
