[package]
name = "rustBotProject"
version = "0.1.0"
edition = "2021"

[dependencies]
noise = "0.7"
rand = "0.8"
axum = "0.6"
tokio = { version = "1", features = ["full"] }
tower = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"